# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hold your head high
subtitle:
description:
keywords:
author: 陆文一
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://git.dev.tencent.com/dtid_91728564d792c8fa/lwy7e.git
#root: /lwy7e/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  prism: true
  tab_replace:
prism_plugin:
  mode: 'preprocess' # realtime/preprocess
  theme: 'tomorrow' # default/prism/tomorrow/okaidia/duotone-dark/duotone-light/coy/dark/funky/atom-material
  line_number: true # default false
  custom_css: '/css/selection.css'
#  custom_js: '/js/codeType.js'
  languages:
    - javascript
    - css
    - php
    - go
    - bash
    - json
    - markdown
    - python
    - sql
    - yaml
    - html
    - java
    - less
    - lua
    - makefile
    - nginx


# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 1
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
  cp /root/redis-5.0.7/redis.conf /etc/redis/6379.conf
  cp /root/redis-5.0.7/utils/redis_init_script /etc/init.d/redisd
  ./redis-server /usr/local/redis-5.0.7/redis.conf
# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
# Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:lwy7e/lwy7e.github.io.git
  branch: master

#deploy:
#  #我们是使用 git 来部署的。
#  type: git
#  # git 仓库的地址。repository
#  repo: https://git.dev.tencent.com/dtid_91728564d792c8fa/lwy7e.git
##  repo: git@git.dev.tencent.com:dtid_91728564d792c8fa/lwy7e.git
#  # 分支名称。
#  branch: master

search:
  path: search.xml
  field: post
  format: html
  limit: 10000
